version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 1
    groups:
      github_actions_all:
        patterns:
          - "*"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
    ignore:
      - dependency-name: "*"
        update-types:
          [
            "version-update:semver-major",
            "version-update:semver-minor",
            "version-update:semver-patch",
          ]

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
    ignore:
      - dependency-name: "toml"
        update-types: ["version-update:semver-major"]
      - dependency-name: "hmac"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]
      - dependency-name: "tower-http"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]
      - dependency-name: "config"
        update-types: ["version-update:semver-major"]
      - dependency-name: "quick-xml"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]
      - dependency-name: "tokio-tar"
      - dependency-name: "axum-core"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]
      - dependency-name: "askama_axum"
        update-types: ["version-update:semver-major"]
      - dependency-name: "testcontainers"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]
      - dependency-name: "testcontainers-modules"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]
      - dependency-name: "rand_chacha"
        update-types: ["version-update:semver-major"]
      - dependency-name: "sha2"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]
      - dependency-name: "axum"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]
      - dependency-name: "rand"
        update-types: ["version-update:semver-major"]
      - dependency-name: "askama"
        update-types: ["version-update:semver-major"]
